### ISSUE TITLE
Clarify ANYLINE_OCR traineddata copying instructions for Android

### ISSUE THREAD

**Issue by Oblongmana** [Anyline/anyline-ocr-react-native-module#31]
Hi there, we've recently licensed the SDK, and we're using the ANYLINE_OCR mode.

I spent spent a few hours today racking my brain trying to work out why the camera wasn't appearing for me, with no apparent errors in the logs.

 After some digging in both the doc at https://documentation.anyline.com/toc/modules/anyline_ocr/index.html, and the doc at https://github.com/Anyline/anyline-ocr-react-native-module, I worked out that when in ANYLINE_OCR mode, the traineddata files need to be copied _by hand_ to `src/main/assets/trainedData`.

The docs at https://documentation.anyline.com/toc/modules/anyline_ocr/index.html mentioned the need to use  `copyTrainedData` - however these instructions are not applicable to the react-native library - this method isn't exposed in a way we could use it (at least not in a maintainable way)

The docs at https://github.com/Anyline/anyline-ocr-react-native-module and https://documentation.anyline.com/toc/platforms/react-native/getting_started.html mention you can put _custom_ traineddata in the referenced directory structure, but don't mention that for Android (but not iOS), you MUST copy traineddata in, even when using the Anyline built-in files.

It all started working fine once I worked that out, thankfully! 😄 

It would be useful for future developers to have some clarification added to the documentation here and on your website. In particular, describing where to find those traineddata files would be useful - I pulled them out of the `ios/Pods/Anyline/AnylineSDK_iOS_3.19.0/Framework/AnylineResources.bundle/module_anyline_ocr/tessdata` folder, but this isn't documented anywhere, and the files aren't in the repo either (rather those files are pulled down during the `pod install`)

**Comment by JonasLaux** [comment]
Hi,
yes you are right, we should make it more clearly, that you need traineddata for you OCR project. Because the ANYLINE_OCR module is a custom one, you need traineddata. In the examples app, the traineddata is uploaded [ios](https://github.com/Anyline/anyline-ocr-react-native-module/tree/master/example/RNExampleApp/ios/trainedData) and [Android](https://github.com/Anyline/anyline-ocr-react-native-module/tree/master/example/RNExampleApp/android/app/src/main/assets/trainedData).
And in the ReadMe it's written down where to put it. But i will improve the documentation on this one. Thanks for mentioning.

**Comment by Oblongmana** [comment]
Brilliant, thanks! Barring the hitch with the torch mentioned in that other issue, the library's working incredibly well so far, keep up the good work :D
