### ISSUE TITLE
[iOS] symbol(s) not found for architecture i386

### ISSUE THREAD

**Issue by craigcoles** [Anyline/anyline-ocr-react-native-module#35]
**Anyline React-Native Plugin version:** 
```JSON
"anyline-ocr-react-native-module": "^3.21.0"
```

**Current behavior:**
Whenever I try and build the app in release, I am experiencing these errors. Works as expected when building in debug mode.

![screen shot 2018-03-15 at 17 09 59](https://user-images.githubusercontent.com/996430/37479132-d0e4466a-2873-11e8-9c22-87c7c175cf1f.png)

**Comment by danielalbertini** [comment]
Hi,

you are getting this error because you are compiling also against the very old i386 simulator architecture. Our SDK is only compiled with the x86_64 simulator architecture. As you are not able to test Anyline in the simulator anyway we only include the newer architecture to save some binary file size.

If you really need to Test your App also on iPhone5 or older simulators you can use #if preprocessor directives. Otherwise you can simply remove the i386 from your architectures list in the xcode build settings.

Best regards,
Daniel

**Comment by craigcoles** [comment]
@danielalbertini These are the current settings I have. I can now get it building in release mode. I had to change Build Active Architecture Only to Yes for both Release and Debug. Is this correct? If not, how you suggested removing i386 architecture from my list, but its not there already?

![screen shot 2018-03-16 at 09 04 52](https://user-images.githubusercontent.com/996430/37512144-29cf5596-28f9-11e8-9932-37b959fdce7e.png)

However, now when I am trying to create an Archive to do an Ad Hoc release, I am getting another Architecture error.

![screen shot 2018-03-16 at 09 06 30](https://user-images.githubusercontent.com/996430/37512214-640b19b6-28f9-11e8-8902-2f4238205c5c.png)

This could be another issue entirely `¯\_(ツ)_/¯ `

**Comment by danielalbertini** [comment]
Sorry for the late reply.

I don't think that this error is related to the Anyline plugin. 

Could you solve the issue?

Best regards,
Daniel
