### ISSUE TITLE
Anyline crashes on React Native 0.62.x

### ISSUE THREAD

**Issue by JBuijgers** [Anyline/anyline-ocr-react-native-module#89]
**Anyline React-Native Plugin version:** 
22 (also tested on version 15 with the same result)

**I'm submitting a ...**  
[ x ] bug report
[ ] feature request
[ ] general question

**Occurring on ...**  
[ x ] Android
[ ] iOS

**Current behavior:**
1. Start Anyline scanner (of any kind).
2. App crashes.

**Expected behavior:**
Working Anyline scanner.

**Steps to reproduce:**
1. Create React Native 0.62.x project
2. Add Anyline dependency.
3. Start Anyline.
4. Crash.

**Related code:**
N/a.

**Other information:**
Worked perfectly on RN v0.61.x using Anyline v15. After upgrading to v0.62.x it crashed by default, tested this on both Anyline v15 and v22.

**Comment by melaniamuir** [comment]
Hi Joost, thanks for reporting the issue! 

Our developers were able to reproduce this behavior. After investigating, they have discovered that there are some open bugs in RN 0.62. This means that the issue is not happening because of the Anyline plugin but because of React Native itself. 

As a workaround please follow these steps: 

1. downgrade to RN 0.61
2. in your project in MainApplication.java comment out:
`initializeFlipper(this, getReactNativeHost().getReactInstanceManager());`

...this Flipper is buggy.

Please let us know if the issue is resolved after following the above workaround. Thank you!

**Comment by JBuijgers** [comment]
Hey @melaniamuir , thanks for the response! I've also tried excluding Flipper from RN 0.62, but the result is the same. After reverting back to RN 0.61, everything worked ok again. Just in case the developers are interested in the stacktrace > https://pastebin.com/7EjK1R9m
